[[redirects]]
  from = "/"
  to = "/aq1.html"

[[redirects]]
  from = "/"
  to = "/aq2.html"  

[[redirects]]
  from = "/"
  to = "/aq3.html"

[[redirects]]
  from = "/"
  to = "/aq4.html"

[[redirects]]
  from = "/"
  to = "/aq5.html"

[[redirects]]
  from = "/"
  to = "/q1.html"    

[[redirects]]
  from = "/"
  to = "/q2.html"  

[[redirects]]
  from = "/"
  to = "/q3.html"  

[[redirects]]
  from = "/"
  to = "/q4.html"  

[[redirects]]
  from = "/"
  to = "/q5.html"    
